Repository kmaengggong/AndCrowd-Backend, pull requests merged in 2023-08, with the labels that each got.

#39 feature/35: Ad, AdPayment Repository, Service CRUD 및 테스트 구현
  andcrowd/src/main/java/com/fiveis/andcrowd/Service/AdPaymentService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/Service/AdPaymentServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/Service/AdService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/Service/AdServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/AdDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/AdPaymentDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/AdPayment.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/AdJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/AdPaymentJPARepository.java
  andcrowd/src/main/resources/application.yml
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/AdJPARepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/AdPaymentJPARepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/AdPaymentServiceTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/AdServiceTest.java
Labels: 김명호

#40 조승연 : crowdCategory에 대한 exception, servic, serviceTest 구현
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/CrowdCategoryDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/exception/Exception
  andcrowd/src/main/java/com/fiveis/andcrowd/exception/NotFoundCrowdCategoryException.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/CrowdCategoryService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/CrowdCategoryServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicAndQnaReplyService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicAndQnaService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/UserSecurityService.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/CrowdCategoryServiceTest.java
Labels: 조승연

#47 feature/45 : CrowdBoard의 Service, ServiceTest 구현
  .idea/vcs.xml
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/DynamicCrowdBoardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/DynamicCrowdQnaReplyRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/DynamicCrowdQnaRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicCrowdBoardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicCrowdBoardServiceImpl.java
  andcrowd/src/main/resources/application.yml
  andcrowd/src/main/resources/mybatis/mapper/DynamicCrowdBoardMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/DynamicCrowdQnaMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/DynamicCrowdQnaReplyMapper.xml
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/DynamicCrowdBoardRepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/DynamicCrowdQnaRepositoryReplyTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/DynamicCrowdQnaRepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/DynamicCrowdBoardServiceTest.java
Labels: 조승연

#49 Feature/24 : AndCategory, AndBoard, AndMember의 Repository, Service, Mapper 코드 작성
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/AndCategoryDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/DynamicAndBoardDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/DynamicAndMemberDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/AndCategoryRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/AndDynamicRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/DynamicAndBoardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/DynamicAndMemberRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/AndCategoryService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/AndCategoryServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicAndBoardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicAndBoardServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicAndMemberService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicAndMemberServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/AndDynamicMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/DynamicAndBoardMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/DynamicAndMemberMapper.xml
Labels: 양현성

#55 Feature/33 : Crowd의 Service - Crowd, OrderDetails, Reward, sponsor 객체 생성, RewardRepo 중복코드 수정, crowdDynamicRepo 생성
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/CrowdDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/CrowdOrderDetailsDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/DynamicRewardDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/DynamicSponsorDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/Crowd.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/CrowdOrderDetails.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/DynamicReward.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/DynamicSponsor.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/DynamicRewardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/CrowdOrderDetailsService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/CrowdOrderDetailsServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/CrowdService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/CrowdServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicRewardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicRewardServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicSponsorService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicSponsorServiceImpl.java
Labels: 오송이

#54 Feature/50 : DynamicAndBoard, DynamicAndMember의 Repository 테스트코드 작성완료
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/DynamicAndBoardDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/DynamicAndMemberDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/DynamicAndBoardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/DynamicAndMemberRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/DynamicRewardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicAndMemberService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/DynamicAndMemberServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/AndDynamicMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/DynamicAndBoardMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/DynamicAndMemberMapper.xml
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/AndDynamicRepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/DynamicAndBoardRepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/DynamicAndMemberRepositoryTest.java
Labels: 양현성

#62 AndDTO 변환 메서드 경로 수정, And Applicant에 andApplyStatus 추가
  .idea/gradle.xml
  .idea/misc.xml
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/AndDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/DynamicAndApplicantDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/DynamicAndApplicant.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/Crowd.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/DynamicAndApplicantMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/DynamicAndQnaReplyMapper.xml
  andcrowd/src/test/java/com/fiveis/andcrowd/service/mysql/ServiceTest.sql
Labels: 임규빈

#73 Feature/61: AndQuery(무한스크롤) 구현 및 And 엔티티, 매퍼 수정
  .idea/compiler.xml
  .idea/modules.xml
  .idea/modules/andcrowd.test.iml
  andcrowd/build.gradle
  andcrowd/src/main/java/com/fiveis/andcrowd/config/JPAConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/And.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndQueryRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndQueryRepositoryImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndQueryService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndQueryServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/and/AndDynamicMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndApplicantMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndBoardMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndMemberMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndQnaMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndQnaReplyMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndRoleMapper.xml
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/and/AndJPARepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/and/AndQueryRepositoryTest.java
  andcrowd/src/test/resources/drop_dummy_data.sql
  andcrowd/src/test/resources/dummy_data.sql
Labels: 임규빈

#77 Feature/53 : DynamicCrowdBoard의 Controller 구현 및 테스트 코드 작성
  andcrowd/src/main/java/com/fiveis/andcrowd/config/BasicSecurityConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdBoardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/CrowdCategoryDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/DynamicCrowdBoardDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/exception/NotFoundCrowdCategoryException.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/CrowdJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdCategoryServiceImpl.java
  andcrowd/src/test/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdBoardControllerTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/crowd/CrowdTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdQnaReplyRepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/and/DynamicAndQnaReplyServiceTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdBoardServiceTest.java
Labels: 조승연

#79 Feature/78 : DynamicCrowdQna의 Controller 구현 및 테스트 코드 작성
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdQnaController.java
  andcrowd/src/test/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdQnaControllerTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdQnaRepositoryTest.java
Labels: 조승연

#81 Feature/66: DynamicUserController 기능 구현
  andcrowd/src/main/java/com/fiveis/andcrowd/config/BasicSecurityConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/DynamicUserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/user/User.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/DynamicUserAndRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/DynamicUserFollowRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/DynamicUserLikeRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/DynamicUserMakerRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/DynamicUserOrderRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/UserJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserAndService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserAndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserFollowService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserFollowServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserLikeService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserLikeServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserMakerService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserMakerServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserOrderService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserOrderServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/user/DynamicUserAndMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/user/DynamicUserFollowMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/user/DynamicUserLikeMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/user/DynamicUserMakerMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/user/DynamicUserOrderMapper.xml
  andcrowd/src/test/java/com/fiveis/andcrowd/controller/user/DynamicUserControllerTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/and/DynamicAndBoardServiceTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/and/DynamicAndMemberServiceTest.java
Labels: 김명호

#84 Feature/74: AndController, AndQnaController 수정
  .idea/misc.xml
  andcrowd/src/main/java/com/fiveis/andcrowd/config/BasicSecurityConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndQnaController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/And.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndQnaServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/and/AndDynamicMapper.xml
  andcrowd/src/test/java/com/fiveis/andcrowd/service/and/AndServiceTest.java
Labels: 임규빈

#94 양현성 : AndCategory, DynamicAndMember 의 Controller 작성완료
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndCategoryController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndBoardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndMemberController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndRoleController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/DynamicAndMemberRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndMemberService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndMemberServiceImpl.java
Labels: 양현성

#90 Feature/83 : DynamicCrowdBoard, DynamicCrowdQna, DynamicCrowdQnaReply에 대한 deleteAll 기능 추가
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdQnaController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdBoardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdQnaReplyRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdQnaRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdQnaReplyServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdQnaService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdQnaServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/crowd/DynamicCrowdBoardMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/crowd/DynamicCrowdQnaMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/crowd/DynamicCrowdQnaReplyMapper.xml
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdBoardRepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdQnaReplyRepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdQnaRepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdBoardServiceTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdQnaReplyServiceTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdQnaServiceTest.java
Labels: 조승연

#93 Feature/91 : CrowdCategory에 대한 서비스 관리자용 기능 구현
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdBoardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdQnaController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdQnaReplyController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/CrowdCategoryDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/DynamicCrowdBoardDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/CrowdCategory.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/DynamicCrowdBoard.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdCategoryService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdCategoryServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdBoardServiceImpl.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/crowd/CrowdCategoryServiceTest.java
Labels: 조승연

#97 Feature/96: 메일 인증 Service, Controller 기능 구현
  andcrowd/build.gradle
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/DynamicUserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/SignController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/UserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/user/UserDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/user/User.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/UserJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/MailService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/MailServiceimpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserServiceImpl.java
Labels: 김명호

#100 Feature/88: and scroll, and role 수정
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndScrollController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndRoleController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/DynamicAndRole.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndQueryRepositoryImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndRoleService.java
Labels: 임규빈
