Repository kmaengggong/AndCrowd-Backend, pull requests merged in 2023-09, with the labels that each got.

#109 Feature/101: And Qna 페이징, And/AndQna 삭제 메서드 수정
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndQnaController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/DynamicAndBoardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/DynamicAndQnaReplyRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/DynamicAndQnaRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndBoardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndBoardServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndQnaReplyService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndQnaReplyServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndQnaService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndQnaServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndBoardMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndQnaMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndQnaReplyMapper.xml
Labels: 임규빈

#114 Feature/111 : Ad, AdPayment Controller 기능 구현
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/AdController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/AdPaymentController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/etc/AdPaymentDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/etc/AdPayment.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/etc/AdPaymentJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/etc/AdPaymentService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/etc/AdPaymentServiceImpl.java
  andcrowd/src/test/java/com/fiveis/andcrowd/controller/etc/AdControllerTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/controller/etc/AdPaymentControllerTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/etc/AdPaymentJPARepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/etc/AdPaymentServiceTest.java
Labels: 조승연

#115 Feature/103-1: 모임 채팅
  .idea/aws.xml
  .idea/compiler.xml
  andcrowd/build.gradle
  andcrowd/gradlew
  andcrowd/src/main/java/com/fiveis/andcrowd/AndcrowdApplication.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/S3Config.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/WebsocketConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/ChatRestController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/FileController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/RoomRestController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/StompChatController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/ChatMessageDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/ChatResponse.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/ChatRoomDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/FileUploadDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/user/UserDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/BaseEntity.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/Chat.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/ChatRoom.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/user/DynamicUserAnd.java
  andcrowd/src/main/java/com/fiveis/andcrowd/enums/ChatStatus.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/ChatRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/ChatRoomRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/ChatRoomService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/ChatService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/FileService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/S3FileService.java
  andcrowd/src/main/resources/application.yml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndMemberMapper.xml
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/user/UserJPARepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/and/ChatRoomServiceTest.java
Labels: 임규빈

#113 Feature/21 : InfoBoard(공지사항게시판) 구현
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/InfoBoardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/etc/InfoBoardDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/etc/InfoBoard.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/etc/InfoBoardJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/etc/InfoBoardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/etc/InfoBoardServiceImpl.java
  andcrowd/src/test/java/com/fiveis/andcrowd/controller/crowd/CrowdControllerTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/controller/etc/InfoBoardControllerTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/etc/InfoBoardJPARepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/etc/InfoBoardServiceTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/mysql/CrowdServiceTest.sql
Labels: 오송이

#118 Feature/116 모임 지원 승인 시 멤버로 추가
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndApplicantController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/DynamicAndApplicantRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/DynamicAndMemberRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndApplicantService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndApplicantServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndMemberService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndMemberServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/and/AndDynamicMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndApplicantMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndMemberMapper.xml
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/and/DynamicAndQnaRepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/and/DynamicAndQnaServiceTest.java
Labels: 임규빈

#121 Feature/99: 김명호: 리프레쉬 토큰, 엑세스 토큰을 이용한 로그인, 회원가입 기능 구현
  andcrowd/.gitignore
  andcrowd/build.gradle
  andcrowd/src/main/java/com/fiveis/andcrowd/config/BasicSecurityConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/CorsFilter.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/TokenAuthenticationFilter.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/jwt/TokenProvider.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/jwt/TokenValidator.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/oauth/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/oauth/OAuth2SuccessHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/oauth/OAuth2UserCustomService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/CustomJsonUserEmailPasswordAuthenticationFilter.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/CustomOAuth2User.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/CustomOAuth2UserService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/JwtAuthenticationFilter.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/LoginFailureHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/LoginSuccessHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/NaverOAuth2UserInfo.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/OAuth2LoginFailureHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/OAuth2LoginSuccessHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/OAuth2UserInfo.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/OAuthAttributesDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/SecurityConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/TokenController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/DynamicUserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/SignController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/UserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/etc/RefreshTokenRequestDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/user/UserDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/etc/RefreshToken.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/user/User.java
  andcrowd/src/main/java/com/fiveis/andcrowd/enums/Authority.java
  andcrowd/src/main/java/com/fiveis/andcrowd/enums/Role.java
  andcrowd/src/main/java/com/fiveis/andcrowd/enums/SocialType.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/etc/RefreshTokenRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/UserJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/etc/RefreshTokenService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/etc/TokenService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/JwtService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserAuthorityService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserSecurityService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/util/CookieUtil.java
  andcrowd/src/main/resources/application.yml
  andcrowd/src/test/java/com/fiveis/andcrowd/controller/user/DynamicUserControllerTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/user/UserJPARepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/user/UserServiceTest.java
Labels: 김명호

#126 Feature/120 : 로그인 유저 정보 받아오기
  .idea/aws 3.xml
  andcrowd/.gitignore
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndApplicantController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/RoomRestController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/UserInfoController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/resources/application.yml
  andcrowd/src/test/java/com/fiveis/andcrowd/service/and/ChatRoomServiceTest 2.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/mysql/CrowdServiceTest 2.sql
Labels: 임규빈

#124 feature/110 : Crowd (Board, QnA, QnAReply, Reward, Sponsor)삭제 메서드 구현
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdRewardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdBoardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdBoardServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdRewardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdRewardServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/crowd/DynamicCrowdRewardMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/crowd/DynamicCrowdSponsorMapper.xml
Labels: 오송이

#130 Feature/125 : 모임장 모임관리 페이지
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndApplicantController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndMemberController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndRoleController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/DynamicAndApplicantDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/DynamicAndMemberDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/DynamicAndRoleDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/DynamicAndMember.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/DynamicAndApplicantRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/DynamicAndMemberRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndApplicantService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndApplicantServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndMemberService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndMemberServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndRoleService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndRoleServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/and/AndDynamicMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndApplicantMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndMemberMapper.xml
  andcrowd/src/test/java/com/fiveis/andcrowd/controller/user/DynamicUserControllerTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/user/UserJPARepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/and/DynamicAndRoleServiceTest.java
Labels: 임규빈

#133 Feature/127 : 모임 제목 검색 추가
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndScrollController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndQueryRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndQueryRepositoryImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndQueryService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndQueryServiceImpl.java
Labels: 임규빈

#135 Feature/132 : 모임 지원에 제목, 첨부파일 추가
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndS3Controller.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/DynamicAndApplicantDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/DynamicAndApplicant.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndS3Service.java
  andcrowd/src/main/resources/application.yml
  andcrowd/src/main/resources/mybatis/mapper/and/AndDynamicMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndApplicantMapper.xml
Labels: 임규빈

#129 Feature/123: UserController및 TokenController 로직 수정
  andcrowd/src/main/java/com/fiveis/andcrowd/config/TokenAuthenticationFilter.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/jwt/TokenProvider.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/TokenController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/DynamicUserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/UserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/user/NaverDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/user/UserDTO.java
Labels: 김명호

#141 Feature/131: 마이 페이지 기능 개선
  andcrowd/.gitignore
  andcrowd/src/main/java/com/fiveis/andcrowd/NaverApiClient.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/BasicSecurityConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/MailConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/NaverAuthCodeRequestUrlProvider.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/NaverOauthConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/NaverToken.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/TokenAuthenticationFilter.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/oauth/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/oauth/OAuth2SuccessHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/oauth/OAuth2UserCustomService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/TokenController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/SignController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/UserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/user/User.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/MailServiceimpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserServiceImpl.java
  andcrowd/src/main/resources/application.yml
Labels: 김명호

#144 Feature/137 : ChatRoomService 멤버 조회시 findAllNotDeleted 로 변경
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/ChatRoomService.java
Labels: 임규빈

#143 Feature/131: 마이페이지 기능 관련 ProjectDTO 컬럼 변경
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/UserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/etc/ProjectDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/user/UserS3DTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserLikeServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserS3Service.java
  andcrowd/src/main/resources/application.yml
Labels: 김명호

#150 feature/146: 메이커 페이지 기능 구현
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/DynamicUserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserMakerService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserMakerServiceImpl.java
Labels: 김명호

#149 feature/148 : CrowdCategory entity, DTO, service, controller 생성 및 수정
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdCategoryController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/CrowdCategoryDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/CrowdCategory.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/CrowdCategoryJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdCategoryService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdCategoryServiceImpl.java
Labels: 오송이

#151 Feature/145 : 모임 조회수, 찜, 팔로우 기능
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/DynamicUserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndQueryRepositoryImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserFollowService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserFollowServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserLikeService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserLikeServiceImpl.java
  andcrowd/src/main/resources/application.yml
Labels: 임규빈

#142 Feature/136 : crowd 새로운 글 생성시 이미지를 업로드 할 수 있는 기능 구현
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdFileController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdS3Controller.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdRewardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdSponsorController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/CrowdS3DTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/ImgUploadDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/Crowd.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/DynamicCrowdReward.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdRewardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdFileService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdS3FileService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdS3Service.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdRewardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdRewardServiceImpl.java
  andcrowd/src/main/resources/application.yml
Labels: 오송이

#158 Feature/154 : 모임 board 페이징, userNickname 메서드
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndBoardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/DynamicAndQnaController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/UserInfoController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/DynamicAndBoardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/UserJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndBoardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndBoardServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/DynamicAndQnaServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/and/DynamicAndBoardMapper.xml
Labels: 임규빈

#162 Feature/159 : 모임 버튼 권한 / 모임 검색 / 채팅 유저 프로필
  .idea/compiler.xml
  .idea/misc.xml
  andcrowd/build.gradle
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndScrollController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/RoomRestController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/UserInfoController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/user/UserDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/And.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/user/User.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/ChatRoomRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/DynamicAndBoardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/UserJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/ChatRoomService.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/and/AndQueryRepositoryTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/crowd/CrowdCategoryServiceTest.java
  andcrowd/src/test/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdRewardServiceTest.java
Labels: 임규빈

#164 Feature/161: 결제 페이지 및 결제 기능 구현
  andcrowd/src/main/java/com/fiveis/andcrowd/config/BasicSecurityConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/jwt/TokenProvider.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/InfoBoardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/ReportController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/TokenController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/UserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/user/UserDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/etc/InfoBoardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/etc/InfoBoardServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserServiceImpl.java
Labels: 김명호

#160 Feature/152: 관리자 기능 및 페이지 추가, 공지사항 페이지 추가
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/UserJPARepository.java
Labels: 김명호

#155 feature/153 : Crowd의 Board repository, service, controller 수정
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdBoardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/DynamicCrowdBoardDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/DynamicCrowdBoard.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdBoardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdRewardRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdBoardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdBoardServiceImpl.java
Labels: 오송이

#168 feature/166 : crowd board, qna, qnaReply 수정
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/DynamicCrowdQnaDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/CrowdOrderDetails.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/DynamicCrowdQna.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/DynamicCrowdQnaReply.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdQnaReplyRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdQnaRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdBoardService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdBoardServiceImpl.java
Labels: 오송이

#170 Feature/161: 소셜 로그인(네이버) 기능 구현
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  andcrowd/src/main/java/com/fiveis/andcrowd/config/BasicSecurityConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/oauth/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/oauth/OAuth2SuccessHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/oauth/OAuth2UserCustomService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdOrderDetailsController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdS3Controller.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdRewardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/TokenController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/SignController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/UserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/CrowdOrderDetailsDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/user/UserDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/CrowdOrderDetails.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/user/User.java
  andcrowd/src/main/java/com/fiveis/andcrowd/enums/SocialType.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/DynamicUserAndRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/DynamicUserFollowRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/DynamicUserLikeRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/DynamicUserMakerRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/user/DynamicUserOrderRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdOrderDetailsService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdOrderDetailsServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdS3Service.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserAndService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserAndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserFollowService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserFollowServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserLikeService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserLikeServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserMakerService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserMakerServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserOrderService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserOrderServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/NaverService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserServiceImpl.java
  andcrowd/src/main/resources/application.yml
  andcrowd/src/main/resources/mybatis/mapper/user/DynamicUserAndMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/user/DynamicUserFollowMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/user/DynamicUserLikeMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/user/DynamicUserMakerMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/user/DynamicUserOrderMapper.xml
Labels: 김명호

#172 Feature/169 : 모임 전체 인원 update
  .idea/aws 2.xml
  .idea/aws 3.xml
  andcrowd/src/main/java/com/fiveis/andcrowd/config/AndEndDateStatusConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/AndController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/UserInfoController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
Labels: 임규빈

#175 Feature/171: Crowd 글쓰기 페이지 및 로직
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdS3ImageController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/Crowd.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/user/User.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdServiceImpl.java
Labels: 김명호

#177 Feature/169 : 펀딩 카테고리, 정렬, 페이징 메서드 추가
  .idea/aws 2.xml
  .idea/aws 3.xml
  .idea/gradle.xml
  .idea/modules.xml
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/CrowdJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/CrowdSpecifications.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdServiceImpl.java
Labels: 임규빈

#179 Feature/178 : 모임/펀딩 마감일 자료형 수정
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/AndDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/CrowdDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/etc/ProjectDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/And.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/Crowd.java
Labels: 임규빈

#184 Feature/180 : 모임 승인 후 채팅방 생성
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/ChatRoomService.java
Labels: 임규빈

#185 Feature/176: 마이페이지 팔로우 유저
  andcrowd/src/main/java/com/fiveis/andcrowd/config/oauth/OAuth2UserCustomService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/TokenController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/DynamicUserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/UserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/CrowdOrderDetailsDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/user/UserDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/CrowdOrderDetails.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/user/User.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserAndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserFollowServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserLikeServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserMakerService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserMakerServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserOrderService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserOrderServiceImpl.java
Labels: 김명호

#181 Feature/174 : crowd의 조회수, 좋아요 기능 추가
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdBoardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdQnaReplyController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/DynamicCrowdBoardDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/Crowd.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/DynamicCrowdBoard.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/DynamicUserLikeServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/crowd/DynamicCrowdBoardMapper.xml
Labels: 오송이

#183 feature/182 : crowd글 생성시 board, qna 작성권한 부여
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdBoardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdQnaReplyController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/Crowd.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/crowd/DynamicCrowdBoardMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/crowd/DynamicCrowdQnaMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/crowd/DynamicCrowdRewardMapper.xml
Labels: 오송이

#188 Feature/186 : 크라우드 인기 게시물 API / 펀딩 <-> 모임 자동 연계 추가
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/CrowdJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/and/AndServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdServiceImpl.java
Labels: 임규빈

#192 Feature/189 : 펀딩 리워드별 판매량 및 총 모금액
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdOrderDetailsController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/CrowdOrderDetailsDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/CrowdOrderDetailsJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdOrderDetailsService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdOrderDetailsServiceImpl.java
  andcrowd/src/test/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdQnaReplyControllerTest.java
Labels: 임규빈

#190 Feature/187 : Crowd Board, qnaReply CRUD 구현
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdQnaReplyController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/CrowdDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/Crowd.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/CrowdJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/DynamicCrowdQnaReplyRepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdBoardServiceImpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdQnaReplyService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/DynamicCrowdQnaReplyServiceImpl.java
  andcrowd/src/main/resources/mybatis/mapper/crowd/DynamicCrowdQnaReplyMapper.xml
  andcrowd/src/main/resources/mybatis/mapper/crowd/DynamicCrowdRewardMapper.xml
Labels: 오송이

#196 Feature/194 : 펀딩 관리자 페이지를 위한 API
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdOrderDetailsController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/CrowdOrderDetailsDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/crowd/CrowdOrderDetailsJPARepository.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdOrderDetailsService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/crowd/CrowdOrderDetailsServiceImpl.java
Labels: 임규빈

#193 김명호: 배포 전 설정
  andcrowd/Dockerfile
  andcrowd/META-INF/MANIFEST.MF
  andcrowd/build.gradle
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/and/QAnd.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/and/QAndCategory.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/and/QBaseEntity.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/and/QChat.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/and/QChatRoom.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/crowd/QCrowd.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/crowd/QCrowdCategory.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/crowd/QCrowdOrderDetails.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/etc/QAd.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/etc/QAdPayment.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/etc/QInfoBoard.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/etc/QRefreshToken.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/etc/QReport.java
  andcrowd/src/main/generated/com/fiveis/andcrowd/entity/user/QUser.java
  andcrowd/src/main/java/com/fiveis/andcrowd/util/CookieUtil.java
Labels: 김명호

#199 Feature/195: 웹훅 테스트 겸 jasypt 적용
  andcrowd/Dockerfile
  andcrowd/build.gradle
  andcrowd/src/main/java/com/fiveis/andcrowd/AndcrowdApplication.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/JasyptConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/jwt/TokenProvider.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/jwt/TokenValidator.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/TokenController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/MailServiceimpl.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/UserS3Service.java
  andcrowd/src/main/resources/application.yml
Labels: 김명호

#201 Feature/200: 시크릿키 수정 - 로그인 관련
  andcrowd/src/main/java/com/fiveis/andcrowd/config/MailConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/NaverAuthCodeRequestUrlProvider.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/NaverOauthConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/NaverToken.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/jwt/TokenProvider.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/CustomJsonUserEmailPasswordAuthenticationFilter.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/CustomOAuth2User.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/CustomOAuth2UserService.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/JwtAuthenticationFilter.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/LoginFailureHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/LoginSuccessHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/NaverOAuth2UserInfo.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/OAuth2LoginFailureHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/OAuth2LoginSuccessHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/OAuth2UserInfo.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/OAuthAttributesDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/temp/filter/SecurityConfig.java
Labels: 김명호

#203 Feature/197 : cross origin 주석처리 , CrowdRewardController findAll -> findAllNotDeleted
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/and/RoomRestController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/CrowdOrderDetailsController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdBoardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdQnaController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdQnaReplyController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdRewardController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/crowd/DynamicCrowdSponsorController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/AdController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/AdPaymentController.java
Labels: 임규빈

#204 Feature/200: 마이페이지 유저 팔로우 수정
  andcrowd/src/main/java/com/fiveis/andcrowd/config/BasicSecurityConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/jwt/JwtProperties.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/jwt/TokenValidator.java
  andcrowd/src/main/java/com/fiveis/andcrowd/config/oauth/OAuth2SuccessHandler.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/TokenController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/user/DynamicUserController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/user/NaverDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/service/user/JwtService.java
Labels: 김명호

#208 Feature/206 : 챗봇 1:1 설정
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/ChatbotController.java
Labels: 임규빈

#209 Feature/200: CorsFilter 지워봄
  andcrowd/src/main/java/com/fiveis/andcrowd/config/CorsFilter.java
Labels: 김명호

#210 Feature/206 : 챗봇 1:1 설정 추가
  andcrowd/src/main/java/com/fiveis/andcrowd/controller/etc/ChatbotController.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/etc/ChatbotMessage.java
Labels: 임규빈

#211 Feature/206 : 빈 컬럼 제거
  andcrowd/src/main/java/com/fiveis/andcrowd/config/BasicSecurityConfig.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/and/AndDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/dto/crowd/CrowdDTO.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/And.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/and/DynamicAndQnaReply.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/crowd/Crowd.java
  andcrowd/src/main/java/com/fiveis/andcrowd/entity/etc/ChatbotMessage.java
  andcrowd/src/main/java/com/fiveis/andcrowd/repository/and/AndQueryRepositoryImpl.java
  andcrowd/src/test/java/com/fiveis/andcrowd/repository/crowd/CrowdJPARepositoryTest.java
Labels: 임규빈
